# https://projecteuler.net/problem=3

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



first_term = 1
second_term = 1
even_sum = 0

while first_term < 4000000:
    temp = first_term
    first_term = first_term + second_term
    if first_term % 2 == 0:
        even_sum = even_sum + first_term
    second_term = temp

print(even_sum)